// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrvpoctrcihfbsjptplh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhydnBvY3RyY2loZmJzanB0cGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDc5OTksImV4cCI6MjA2MzQyMzk5OX0.c6hAMU0vgjoa-Kii-vI8N2LI-XGwjLK1ZvvpIJfq_NU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);